# .github/workflows/keep-alive.yml
name: Keep Render Alive

# This uses UTC; '*/14 * * * *' = every 14 minutes
on:
  schedule:
    - cron: '*/14 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: curl -s https://shopname.onrender.com > /dev/null
